# Application configuration
#
# This file defines all configuration values for a mangoo I/O application.
# The default values are loaded by default and overwritten by environment specific
# values if they are configured.
#
# Possible environments are test and dev.
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

default:
    application:
        name       : TEST
        secret     : myvoiceismypasswordmyvoiceismypassword
        language   : en
        host       : localhost
        port       : 9898
        jwt        :
            signkey       : myvoiceismypassword
            encrypt       : true
            encryptionkey : myvoiceismypasswordmyvoiceismypa
        timer      : true
        minify:
            js        : true
            css       : true
        preprocess:
            js        : true
            css       : true
    connector:
        http:
            host      : localhost
            port      : 9898
        ajp:
            host      : localhost
            port      : 9899
    cookie:
       encrypt : true
    auth:
        redirect  : /login
        cookie:
            name    : TEST-AUTH
            encrypt : false
            expires : 3600
    oauth:
        twitter:
            key       : ###
            secret    : ###
            callback  : http://localhost:50000/authenticate?oauth=twitter
        google:
            key       : ###
            secret    : ###
            callback  : http://localhost:50000/authenticate?oauth=google
        facebook:
            key       : ###
            secret    : ###
            callback  : http://localhost:50000/authenticate?oauth=facebook
    cookie:
        name       : TEST-SESSION
        expires    : 86400
        encryption : false
    smtp:
        host       : localhost
        port       : 25
        username   : foo
        password   : bar
        ssl        : false

test:
    application:
        foo              : cryptex[xOh1oRZzZNfBVl8Sw+O/OTqafBVD6ISKGjSmbljt/hw=]
        admin:
              enable     : true
              username   : admin
              password   : $2a$12$eEIuI88oeA7zcqZgPBsM8OsqFCZuoyxzqgWVJDUDddUUIfvR.I7Uy
    connector:
        http:
            host      : localhost
            port      : 10808
        ajp:
            host      : localhost
            port      : 10809
    smtp:
        port       : 3055
        username   :

dev:
    application:
        admin:
              enable     : true
              username   : admin
              password   : $2a$12$eEIuI88oeA7zcqZgPBsM8OsqFCZuoyxzqgWVJDUDddUUIfvR.I7Uy
    connector:
        http:
            host      : localhost
            port      : 50000
        ajp:
            host      : localhost
            port      : 50001
    smtp:
        port       : 3125
