default:
  application:
    name: arg{}
    url: arg{http://localhost:4223}
    secret: Jb3MenqcohfVQNi3mYBBoYGk8JQ94u5cvEWz9rZMR1EED9t3l8eWwuF1jyXLDzvvZpMznuWeOlnfcNss0qlimeK8MA5McCCPeo2fhC
    language: en
    allowedOrigins: http://foo.de, http://bar.de
    minify:
      js: true
      css: true
    encrypted: arg{}
    named: shouldnotbedisplayed
    admin:
      secret: ""
    paseto:
      secret: QLxhAXDh6PjAhFVY2kMMrQrdlaWDUP7E1PC4pBuDe9zSCH2Suvv
    api:
      key: ZU799ZHnRwPEzBUfkG49VWbtmIlhhqWsY2kMMrQrdlardlaWDUP7E1PC4prdlaWDUP7E1PC4p
  connector:
    http:
      host: localhost
      port: 9898
    ajp:
      host:
      port: 9899
  session:
    cookie:
      name: test-session
      secret: o5orE4lGoOM66HpOxuE9VVt1xuIefbmi7D6HFTpcDCwt4PoXH41wSi50jy8NkAcL
  flash:
    cookie:
      name: test-flash
      secret: lbJ4VKPcAeyqGmHjGt2YiQKTLRRxdHHKbrL2cEwPGIgfoHWGjViNLkOYGpPJ8dI3
  metrics:
    enable: true
  authentication:
    redirect:
      login: /login
    cookie:
      name: test-authentication
      secret: oObVaXmpokhImaLyCtg8lzL1PC4pBuDe9zSCH2Suvv2eSN2b4UUDtBcFlyq5JEHB
  smtp:
    host: localhost
    port: 25
    protocol: smtp

environments:
  test:
    application:
      foo: vault{}
      bar: vault{}
      foobar: vault{}
      admin:
        enable: true
        username: vault{}
        password: vault{}
        locale: de_DE
        health:
          enable: true
          token: tZEwV79iJMbcDI3Tf0QqcaP6USCIXBBUavXt1MgQkb546UwU9h5HPEpOSlVBZLMR
      test: arg{}
      named: injected
      profil: arg{}
    connector:
      http:
        host: localhost
        port: 10808
      ajp:
        host: localhost
        port: 10809
    smtp:
      port: 3025
      username: bla
    cors:
      enable: true
      alloworigin: ^localhost$|^127(?:\.[0-9]+){0,2}\.[0-9]+$|^(?:0*\:)*?:?0*1$
      urlpattern: ^http(s)?://([^/]+)(:([^/]+))?(/([^/])+)?/api(/.*)?$
      headers:
        allowcredentials: true
        allowheaders: Content-Range,ETag
        allowmethods: GET,POST,PATCH
        exposeheaders: Authorization,Content-Type
        maxage: 86400
    persistence:
      mongo:
        embedded: true
        host: localhost
        port: 29019
        package: models
        dbname: test
      myprefix:
        embedded: true
        host: localhost
        port: 29019
        package: models
        dbname: test

  dev:
    application:
      name: integration-test
      admin:
        enable: true
        health: true
        username: admin
        password: admin
        locale: de_DE
    connector:
      http:
        host: localhost
        port: 8080
      https:
        host: localhost
        port: 8443
    smtp:
      port: 3125
    persistence:
      mongo:
        embedded: true
        host: localhost
        port: 29019
        package: models
        dbname: test
      myprefix:
        embedded: true
        host: localhost
        port: 29019
        package: models
        dbname: test
