routes:
# Routes configuration
#
# This file defines all application routes.
# All routes start with an identifier of the method, followed by the
# url, followed by a mapping to the controller class and method. For
# some types a controller and method is not required.
#
# You can find a detailed explation of the routing file in the documentation
# https://mangoo.io/documentation#_routes
#
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# BasicAuthenticationController
- method: GET
  url: /basicauth
  mapping: BasicAuthenticationController.basicauth
  username: foo
  password: $2a$12$Po56ZgZQgDEoK6nws6gaAuZriIwcFT1thEHq.N2T9wLdUnhmlLKxG

# FilterController
- method: GET
  url: /filter
  mapping: FilterController.filter

- method: GET
  url: /headerfilter
  mapping: FilterController.headerfilter

- method: GET
  url: /filters
  mapping: FilterController.filters

# I18nController
- method: GET
  url: /translation
  mapping: I18nController.translation

- method: GET
  url: /messages
  mapping: I18nController.messages

- method: GET
  url: /special
  mapping: I18nController.special

- method: GET
  url: /umlaute
  mapping: I18nController.umlaute

- method: GET
  url: /localize
  mapping: I18nController.localize

# FlashController
- method: GET
  url: /flash
  mapping: FlashController.flash

- method: GET
  url: /flashed
  mapping: FlashController.flashed

# AuthenticationController
- method: POST
  url: /dologin
  mapping: AuthenticationController.doLogin

- method: POST
  url: /login
  mapping: AuthenticationController.login

- method: GET
  url: /login
  mapping: AuthenticationController.login

- method: GET
  url: /subject
  mapping: AuthenticationController.subject

- method: GET
  url: /authenticationrequired
  mapping: AuthenticationController.notauthenticated

- method: GET
  url: /authenticate
  mapping: AuthenticationController.authenticate

- method: GET
  url: /logout
  mapping: AuthenticationController.logout

# SessionController
- method: GET
  url: /session
  mapping: SessionController.session

- method: GET
  url: /session/valued/{uuid}
  mapping: SessionController.valued

# ParameterController
- method: GET
  url: /string/{foo}
  mapping: ParameterController.stringParam

- method: GET
  url: /optional/{foo}
  mapping: ParameterController.optionalParam

- method: GET
  url: /string
  mapping: ParameterController.stringParam

- method: GET
  url: /int/{foo}
  mapping: ParameterController.intParam

- method: GET
  url: /integer/{foo}
  mapping: ParameterController.integerParam

- method: GET
  url: /doublePrimitive/{foo}
  mapping: ParameterController.doublePrimitiveParam

- method: GET
  url: /double/{foo}
  mapping: ParameterController.doubleParam

- method: GET
  url: /float/{foo}
  mapping: ParameterController.floatParam

- method: GET
  url: /floatPrimitive/{foo}
  mapping: ParameterController.floatPrimitiveParam

- method: GET
  url: /longPrimitive/{foo}
  mapping: ParameterController.longPrimitiveParam

- method: GET
  url: /long/{foo}
  mapping: ParameterController.longParam

- method: GET
  url: /multiple/{foo}/{bar}
  mapping: ParameterController.multipleParam

- method: GET
  url: /path
  mapping: ParameterController.pathParam

- method: GET
  url: /localdate/{localDate}
  mapping: ParameterController.localdate

- method: GET
  url: /localdatetime/{localDateTime}
  mapping: ParameterController.localdatetime

# AuthenticityController
- method: GET
  url: /authenticityform
  mapping: AuthenticityController.form

- method: GET
  url: /authenticitytoken
  mapping: AuthenticityController.token

- method: GET
  url: /valid
  mapping: AuthenticityController.valid

- method: GET
  url: /invalid
  mapping: AuthenticityController.invalid

#JsonController
- method: GET
  url: /render
  mapping: JsonController.render

- method: POST
  url: /parse
  mapping: JsonController.parse

- method: PUT
  url: /parse
  mapping: JsonController.parse

- method: PATCH
  url: /parse
  mapping: JsonController.parse

- method: POST
  url: /body
  mapping: JsonController.body

- method: POST
  url: /requestAndJson
  mapping: JsonController.requestAndJson

# FormController
- method: POST
  url: /form
  mapping: FormController.form

- method: POST
  url: /multivalued
  mapping: FormController.multivalued

- method: POST
  url: /submit
  mapping: FormController.submit

- method: GET
  url: /flashify
  mapping: FormController.flashify

- method: POST
  url: /singlefile
  mapping: FormController.singlefile

- method: POST
  url: /multifile
  mapping: FormController.multifile

- method: POST
  url: /validateform
  mapping: FormController.validateform

# ApplicationController
- method: GET
  url: /
  mapping: ApplicationController.index
  blocking: true
  timer: true

- method: GET
  url: /route
  mapping: ApplicationController.route

- method: POST
  url: /
  mapping: ApplicationController.index

- method: PUT
  url: /
  mapping: ApplicationController.index

- method: PATCH
  url: /
  mapping: ApplicationController.index

- method: HEAD
  url: /
  mapping: ApplicationController.index

- method: DELETE
  url: /
  mapping: ApplicationController.index

- method: OPTIONS
  url: /
  mapping: ApplicationController.index

- method: GET
  url: /reverse
  mapping: ApplicationController.reverse

- method: GET
  url: /restricted
  mapping: ApplicationController.restricted

- method: GET
  url: /location
  mapping: ApplicationController.location

- method: GET
  url: /prettytime
  mapping: ApplicationController.prettytime

- method: GET
  url: /location/{myloca}
  mapping: ApplicationController.location

- method: GET
  url: /redirect
  mapping: ApplicationController.redirect

- method: GET
  url: /limit
  mapping: ApplicationController.limit
  limit: 10

- method: GET
  url: /text
  mapping: ApplicationController.text

- method: GET
  url: /forbidden
  mapping: ApplicationController.forbidden

- method: GET
  url: /badrequest
  mapping: ApplicationController.badrequest

- method: GET
  url: /unauthorized
  mapping: ApplicationController.unauthorized

- method: GET
  url: /binary
  mapping: ApplicationController.binary

- method: GET
  url: /header
  mapping: ApplicationController.header
  blocking: true

- method: GET
  url: /etag
  mapping: ApplicationController.etag

- method: GET
  url: /request
  mapping: ApplicationController.request

- method: POST
  url: /post
  mapping: ApplicationController.post

- method: PUT
  url: /put
  mapping: ApplicationController.put

- method: POST
  url: /jsonpathpost
  mapping: ApplicationController.jsonPathPost

- method: PUT
  url: /jsonpathput
  mapping: ApplicationController.jsonPathPut

- method: POST
  url: /jsonboonpost
  mapping: ApplicationController.jsonBoonPost

- method: PUT
  url: /jsonboonput
  mapping: ApplicationController.jsonBoonPut

# Controllers in Sub Packages
- method: GET
  url: /subcontroller
  mapping: subcontrollers.SubController.check

# WebSocketController
- method: WSS
  url: /websocket
  mapping: WebSocketController

- method: WSS
  url: /websocketauth
  mapping: WebSocketController
  authentication: true

# ServerSentEvent
- method: SSE
  url: /sse

- method: SSE
  url: /sseauth
  authentication: true

# Resource path and resource files
- method: PATH
  url: /assets/

- method: FILE
  url: /robots.txt
