default:
    application:
        name       : ${application-name} 
        secret     : ${application-secret}
        language   : en
        host       : localhost
        port       : 8080
        minify:
            js        : false
            css       : false
            jsfolder  : /foo
            cssfolder : /bar
            gzipjs    : false
            gzipcss   : false
        auth:
            redirect  : /login
            cookie:
                name    : ${application-name} -AUTH
                encrypt : false
                expires : 86400
    cookie:
        name       : ${application-name} -SESSION
        expires    : 86400
        encryption : false
    smtp:
        host       : localhost
        port       : 25
        username   : 
        password   : 
        ssl        : false
        
test:
    application:
        port       : 10808
    smtp:
        port       : 3055
        
dev:
    smtp:
        port       : 3025